// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfzavluourjxscqdtfpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5memF2bHVvdXJqeHNjcWR0ZnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTQ1MDYsImV4cCI6MjA2MDQ3MDUwNn0.xb5NfEvOxkf4TAeds7Bxsu5tEFuPss7TEa0y3VR-zKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);